# Site Configuration
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yahir Mesa
title: Assistant Manager
email: yahirmesa101@gmail.com
website: Yahirmesa101.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username: sproogen
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: globalmtb
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Yahir Mesa, and I am a results-driven manager with extensive experience in fast-paced, customer-focused environments. Throughout my career, I have honed my skills in leading high-performing teams, optimizing sales strategies, and delivering exceptional service in fast food and retail settings. 

  Currently, I am working on transitioning into other markets, leveraging my proven expertise in inventory control, merchandising, and client relationship management. I am passionate about creating memorable shopping experiences that drive revenue growth and foster brand loyalty.

  I am most skilled in:
  - <mark>Managing Teams</mark>
  - <mark>Eating Pizza</mark>

  I believe in the power of teamwork, and I thrive in environments where innovation and collaboration are encouraged.

# Content Sections
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>React</mark> and it has since grown into a fully-fledged app. I have learned many skills through this, and I'm very proud of having this in my portfolio. If you don't have a project as awesome as this, I would advise you to make one.
  - title: Experience # Title for the section
  layout: list # Type of content section (list/text)
  content:
    - layout: center
      title: Wendy's
      link: https://shorturl.at/iawnC
      sub_title: Assistant Manager
      caption: January 2020 - Present
      location: >
        352 Motor Parkway, Hauppauge, New York
      quote: >
        "El éxito es la suma de pequeños esfuerzos repetidos día tras día." – Anónimo  
      translation: >
        "Success is the sum of small efforts repeated day after day." – Anonymous  
      description: | # This allows new lines for readability
        As an Assistant Manager at Wendy’s, I played a key role in ensuring smooth day-to-day operations.  
        From leading a team during peak hours to optimizing workflows for efficiency, I focused on delivering excellent customer service and maintaining a positive work environment.  
        My responsibilities included training new employees, managing inventory, and ensuring compliance with company policies—all while keeping the team motivated and engaged.  

    - layout: center
      title: Wendy's
      link: https://shorturl.at/xJEqc
      sub_title: Interim Store Manager
      caption: February 2022 - December 2022
      location: >
        5212 Spring Valley Rd., Dallas, Texas
      quote: >
        "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.  
        Si amas lo que haces, tendrás éxito." – Anónimo  
      translation: >
        "Success is not the key to happiness. Happiness is the key to success.  
        If you love what you do, you will succeed." – Anonymous  
      description: |  
        As an Interim Store Manager, I took on greater responsibilities, overseeing the store’s overall performance.  
        I managed scheduling, financial reporting, and led the team through high-volume shifts while maintaining operational excellence.  
        My focus was on enhancing team dynamics, increasing customer satisfaction, and streamlining processes to drive sales and efficiency.  
        This role strengthened my leadership skills and adaptability in a fast-paced, customer-driven environment.  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard, I learned most of the key skills that have carried me through my career, such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at university and learned a lot about maintaining a healthy work-life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club*, taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering, some of my other interests and hobbies include:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
